export const UPDATE_PREFS = 'UPDATE_PREFS';
export const UPDATE_PERIODS = 'UPDATE_PERIODS';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_THEME = 'SET_THEME';
export const SET_AUTO_REMINDER = 'SET_AUTO_REMINDER';