export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'REMDELETE_TASKOVE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const UPDATE_NEW_TASK_DATA = 'UPDATE_NEW_TASK_DATA';
export const CHOOSE_TASK_TO_EDIT = 'CHOOSE_TASK_TO_EDIT';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const CHANGE_GESTURE_POSITIONS = 'CHANGE_GESTURE_POSITIONS';