export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'REMDELETE_TASKOVE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const SET_TASK_EXPIRATION = 'SET_TASK_EXPIRATION';
export const UPDATE_POSITIONS = 'UPDATE_POSITIONS';